### ISSUE TITLE
Youtube URL pattern with trailing slash

### ISSUE THREAD

**Issue by hugovieilledent** [regexps/youtube-regex#3]
Hello,

It seems like this URL with a trailing slash after `watch` is a valid Youtube URL.
`https://www.youtube.com/watch/?v=v2ifWcnQs6M`

I haven't seen it offered officially by Youtube, but some of our users submitted links (that failed) with such slash.

Is is something you could support?
Anyway thank you for offering this module.

Cheers,
Hugo

**Comment by tunnckoCore** [comment]
Hi and sorry for the delay.

Good catch, thanks!

**Comment by tunnckoCore** [comment]
@hugovieilledent thanks again!
More reports and help about #2 welcome!
